chore(titus): limit protobuf to 3.17.3 (#5706) (#5712)
On May 11, builds (e.g. https://github.com/spinnaker/clouddriver/runs/6395450456?check_suite_focus=true, https://github.com/spinnaker/clouddriver/runs/6396984248?check_suite_focus=true and https://github.com/spinnaker/clouddriver/runs/6396922814?check_suite_focus=true) started failing with e.g.:

> Task :clouddriver-titus:compileJava
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountId_)) {
                                                 ^
  symbol:   method isStringEmpty(Object)
  location: class GeneratedMessageV3
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/java/com/netflix/titus/TitusVpcApi.java:413: error: cannot find symbol

According to https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-java/,
com.google.protobuf:3.21.0-rc-1 arrived on May 11, but pinning to the latest version
before that (3.20.1) doesn't work either.  Neither do 3.19.x nor 3.18.x.  3.17.3 is the
newest version that works.

(cherry picked from commit 10a8d09695ae5fc3455b0993283c1c0e0f1dd329)

Co-authored-by: David Byron <82477955+dbyron-sf@users.noreply.github.com>