fix(sql/test): render list as a string in saga_ids field of tasks table in SqlTaskCleanupAgentTest
jooq 3.14.16 complains:

        Caused by:
        java.sql.SQLException: Error while writing value at JDBC bind index: 5
            at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:67)
            at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124)
            ... 120 more

            Caused by:
            org.jooq.exception.SQLDialectNotSupportedException: Type class java.util.ArrayList is not supported in dialect MYSQL

Even if jooq doesn't complain, this feels like the more correct way to provide a value for
this field, and matches what SqlTaskRepository does.