fix(aws): Fix bug in AWS provider after Groovy 3 upgrade (#6142)
* fix(aws): Fix bug in AWS provider after Groovy 3 upgrade

I'm unsure how this code has ever worked, but after the upgrade to Groovy 3, it started crashing.

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '{loadBalancers=aws:loadBalancers:my-aws-account:eu-west-1:*:vpc-????????:*}' with class 'java.util.LinkedHashMap' to class 'java.util.Optional' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.Optional(LinkedHashMap)
```

* Add tests

(cherry picked from commit b19a9064c9f02ce7429c99de6c5d2df632c6b2da)