fix(dependency): Issue of missing javax.validation:validation-api dependency while upgrading the spring cloud to Hoxton.SR12 in kork
While upgrading spring cloud to Hoxton.SR12, we encountered below issues :

/clouddriver/clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsConverter.java:27: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
/clouddriver/clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsConverter.java:44: error: cannot find symbol
  public T getCredentialsObject(@NotNull final String name) {
                                 ^
  symbol:   class NotNull
  location: class AbstractAtomicOperationsCredentialsConverter<T>
  where T is a type-variable:
    T extends AccountCredentials<?> declared in class AbstractAtomicOperationsCredentialsConverter
/clouddriver/clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/security/AbstractAtomicOperationsCredentialsConverter.java:43: error: cannot find symbol
  @NotNull
   ^
  symbol:   class NotNull
  location: class AbstractAtomicOperationsCredentialsConverter<T>
  where T is a type-variable:
    T extends AccountCredentials<?> declared in class AbstractAtomicOperationsCredentialsConverter
3 errors

The root cause is missing javax.validation:validation-api dependency, the reason being upgrade of transitive dependency resilience4j from 1.0.0 to 1.7.0 while upgrade to Hoxton.SR12.

https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-framework-common/1.0.0

https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-framework-common/1.7.0

To fix this issue we require to explicitly implement the dependency in clouddriver-core.gradle.