fix(titus/build): use version 1.37.1 of io.grpc.* to fix compiler errors
> Task :clouddriver-titus:compileJava FAILED
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/LoadBalancerServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/JobManagementServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/EvictionServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/SupervisorServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/TaskRelocationServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/AutoScalingServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/ResourceConsumptionServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/ResourceAllocationServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/ResourceAllocationArchiveServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/TaskManagementServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/MachineServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/TaskManagementArchiveServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/AgentManagementServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/ClusterMembershipServiceGrpc.java:14: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/SchedulerServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/HealthGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/UserIPServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
/home/runner/work/clouddriver/clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/ValidatorIPServiceGrpc.java:10: error: cannot find symbol
@io.grpc.stub.annotations.GrpcGenerated
                         ^
  symbol:   class GrpcGenerated
  location: package io.grpc.stub.annotations
18 errors

Note that before this PR, gradle used version 1.27.2 of io.grpc.*:

$ ./gradlew :clouddriver-titus:dI --dependency io.grpc:grpc-stub

> Task :clouddriver-titus:dependencyInsight
io.grpc:grpc-stub:1.27.2 (by constraint)
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes+resources)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]

io.grpc:grpc-stub:1.27.2
\--- io.spinnaker.kork:kork-bom:7.116.0
     \--- compileClasspath

io.grpc:grpc-stub:[1.10.0,) -> 1.27.2
\--- compileClasspath

I haven't been able to find a place in kork that specifies anything for io.grpc, nor where
1.27.2 comes from.  I chose version 1.37.1 because it's the newest version that works, yet
sticks with guava 30.0-jre.  Anything newer and we end up with 30.1-android.  Now we have:

$ ./gradlew :clouddriver-titus:dI --dependency io.grpc:grpc-stub

> Task :clouddriver-titus:dependencyInsight
io.grpc:grpc-stub:1.37.1
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes+resources)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - By constraint
      - By conflict resolution : between versions 1.37.1 and 1.27.2

io.grpc:grpc-stub:1.37.1
\--- compileClasspath

io.grpc:grpc-stub:1.27.2 -> 1.37.1
\--- io.spinnaker.kork:kork-bom:7.116.0
     \--- compileClasspath