chore(dependencies): pin version of com.github.tomakehurst:wiremock (#5845)
for more predictable builds, and to avoid failures like:

org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [com.github.tomakehurst.wiremock.WireMockServer arg0] in method [void com.netflix.spinnaker.clouddriver.artifacts.http.HttpArtifactCredentialsTest.downloadWithBasicAuth(com.github.tomakehurst.wiremock.WireMockServer) throws java.io.IOException]: jakarta/servlet/DispatcherType

that come with version 3.0.0-beta2 of com.github.tomakehurst:wiremock released on 30-dec-22.

Use com.github.tomakehurst:wiremock-jre8-standalone as it's the more modern version of wiremock, and has fewer dependencies than wiremock-jre8.

Currently, we end up with version 2.31.0 via spring-cloud-dependencies.  See https://github.com/spring-cloud/spring-cloud-release/blob/v2020.0.5/spring-cloud-dependencies/pom.xml#L25 and https://github.com/spring-cloud/spring-cloud-contract/blob/v3.0.5/spring-cloud-contract-dependencies/pom.xml#L18.

(cherry picked from commit 6c30c181b9f92e0f3c80c5dec547b1c20315246b)