chore(build): try a bigger stack
since the builds (e.g. https://github.com/spinnaker/clouddriver/actions/runs/8015292221/job/21914062873) keep failing.

> Task :clouddriver-ecs:integrationTest
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 830
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "mysql-cj-abandoned-connection-cleanup"